name: "CI (Integração Contínua): Main Workflow"

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Directory Access 
        run: cd github-actions-frontend

      - name: Run Installation
        run: yarn install

      - name: Run Linter
        run: yarn lint